[package]
name = "catpics"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.39"
reqwest = {version="0.12.19",features=["blocking"]}

[profile.release]
strip = true
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
