[package]
name = "catpics"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.39"
reqwest = {version="0.12.19",features=["blocking"]}
viuer = {version="0.9.1",features=["print-file"]}

[profile.release]
strip = true
panic = "abort"
opt-level = "z"
lto = true
